## NumPy: Numerical Python

Permite trabalhar com vetores e matrizes de $N$ dimensões, de uma forma comparável e com uma sintaxe semelhante ao Matlab. É uma poderosa biblioteca do Python que fornece um grande conjunto de funções e operações que ajudam na realização de cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

* **Modelos de Machine Learning:** os arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.

* **Processamento de Imagem e Computação Gráfica**: imagens no computador são representadas como arrays multidimensionais de números. O NumPy fornece algumas excelentes funções de biblioteca para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.

* **Tarefas matemáticas**: é bastante útil para executar várias tarefas matemáticas como integração numérica, diferenciação, interpolação e muitas outras. O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios. 

<img src="../Figuras/python_matlab.png" alt="drawing" width="500"/>

*Fonte*: https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355

In [1]:
#!pip3 install numpy #instalação da biblioteca no próprio notebook

In [2]:
import numpy as np 

Um **array NumPy** é uma extensão de um **array Python** (listas), que lida apenas com arrays unidimensionais.

In [3]:
minha_lista = [1, 2, 3, 4, 5]
print('Array Python (Listas):', minha_lista, ' -> Tipo:', type(minha_lista))
print()
meu_array = np.array(minha_lista)
print('Array NumPy:', meu_array, ' -> Tipo:', type(meu_array))

Array Python (Listas): [1, 2, 3, 4, 5]  -> Tipo: <class 'list'>

Array NumPy: [1 2 3 4 5]  -> Tipo: <class 'numpy.ndarray'>


In [4]:
minha_lista*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
meu_array*2

array([ 2,  4,  6,  8, 10])

O **ndarray**, um objeto fundamental do NumPy, é uma matriz $n$-dimensional, isso significa que ele contém uma **coleção de elementos do mesmo tipo** (dados homogêneos) indexados usando $n$ números inteiros (dimensão da matriz).

Todo array possui uma forma (`shape`), uma tupla indicando o tamanho de cada dimensão e um `dtype`, um objeto que descreve o tipo de dados da matriz. 

## Tipo Array

### Criando ndarrays

In [6]:
dados1 = [1, 1.5, 2, 2.5]
arr1 = np.array(dados1)
print(arr1)
arr1

[1.  1.5 2.  2.5]


array([1. , 1.5, 2. , 2.5])

Sequências aninhadas, como uma lista de listas de igual comprimento, serão convertidas em uma matriz multidimensional:

In [7]:
dados2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(dados2)
print(arr2)
arr2

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
dados3 = [[1, 2, 3, 4], [5, 6, 7]] # sublistas de tamanhos diferentes não são convertidas em uma matriz
arr3 = np.array(dados3)
print(arr3)
arr3

[list([1, 2, 3, 4]) list([5, 6, 7])]


array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [9]:
print('Dimensão de arr1:', arr1.ndim)
print('Shape de arr1:', arr1.shape)
print()
print('Dimensão de arr2:', arr2.ndim)
print('Shape de arr2:', arr2.shape)
print()
print('Dimensão de arr3:', arr3.ndim)
print('Shape de arr3:', arr3.shape)

Dimensão de arr1: 1
Shape de arr1: (4,)

Dimensão de arr2: 2
Shape de arr2: (2, 4)

Dimensão de arr3: 1
Shape de arr3: (2,)


In [10]:
shape2 = arr2.shape
print('O arr2 possui', shape2[0], 'linhas e', shape2[1], 'colunas.')

O arr2 possui 2 linhas e 4 colunas.


A menos que seja explicitamente especificado, o `np.array` tenta inferir um bom tipo de dados para a matriz que ele cria. O tipo de dados é armazenado em um objeto de metadados `dtype` especial.

In [11]:
print('Tipo de dados de arr1:', arr1.dtype)
print('Tipo de dados de arr2:', arr2.dtype)

Tipo de dados de arr1: float64
Tipo de dados de arr2: int64


Se você tiver um array de strings representando números, poderá usar `astyp(float)` para converter os dados para a forma numérica:

In [12]:
np.array(['1', '1.5', '2', '2.5']).astype(float)
#np.array(['1', '1.5', '2', '2.5']).astype(int) # dá erro! 

array([1. , 1.5, 2. , 2.5])

In [13]:
np.array([1, 1.5, 2, 2.5]).astype(int)

array([1, 1, 2, 2])

Além do `np.array`, podemos criar arrays de outras formas. 

* `np.zeros` e `np.ones` criam arrays de 0s ou 1s, respectivamente, com um determinado comprimento.


* `np.empty` cria um array sem inicializar seus valores para qualquer valor específico.


Para criar arrays multidimensionais com esses métodos, passamos como parâmetro de entrada uma tupla com o tamanho desejado. 

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.empty((2, 3, 2))

array([[[ 2.68156159e+154, -4.34329376e-311],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 2.12199579e-314,  2.92966904e-033]],

       [[ 5.00343564e-090,  1.91755886e-076],
        [ 8.46514216e+164,  2.35852961e+180],
        [ 3.99910963e+252,  8.34404888e-309]]])

**Obs.:** não podemos supor que `np.empty` retornará sempre uma matriz com todos os elemntos iguais a zero. Em alguns casos, pode retornar valores não inicializados de "lixo".

Outros métodos de criar um array.

In [17]:
np.arange(20)  # ==> np.arange(0,20,1) | (início, fim, passo)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
np.arange(1,5,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [20]:
# Cria uma sequência de números uniformemente espaçados entre os limites dado
np.linspace(1,10,30) # (início, fim, número de pontos)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [21]:
# linspace(start, stop, num=50)
np.linspace(1,50) # o default é num=50

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [22]:
# Alguns exemplos de arrays com números aleatórios
print(np.random.random(5))
print()
print(np.random.randint(1,11,(2,3)))

[0.8667263  0.53838379 0.73270177 0.13889455 0.14706837]

[[9 9 3]
 [5 4 3]]


In [23]:
# Matriz Identidade de ordem n (matriz quadrada nxn)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
print(np.eye(3))
print()
print(np.eye(3, 4))
print()
print(np.eye(3, 4, 1)) # matriz 3x4, com a diagonal acima da principal contendo as unidades

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
# Modificando as dimensões do array criado
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
b = a.reshape(4,25)
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [27]:
b2 = np.arange(100).reshape(2,10,5)
b2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

### Operações Aritméticas

Qualquer operação aritmética entre arrays de tamanho igual aplica a operação elemento a elemento.

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [30]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr2 = np.array([[0, 4, 1], [7, 2, 12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [33]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [34]:
arr3 = np.array([10,20,30])

In [35]:
arr*arr3

array([[ 10,  40,  90],
       [ 40, 100, 180]])

### Indexação Simples e "Fatiamento"

Os itens de um array podem ser acessados e atribuídos da mesma forma que outras sequências do Python, como listas por exemplo.

Semelhante às listas, arrays também podem ser "fatiados". Como os arrays podem ser multidimensionais, você deve especificar uma "fatia" para cada dimensão do array. 

In [36]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[5]

6

In [38]:
arr[5:8]

array([6, 7, 8])

In [39]:
arr[5:8] = 12 # o valor atribuído será propagado para toda a seleção
arr

array([ 1,  2,  3,  4,  5, 12, 12, 12,  9, 10])

Diferentemente do que ocorre com as listas, as "fatias" dos arrays são visualizações da matriz original. Isso significa que os dados não são copiados e quaisquer modificações dessas "fatias" serão refletidas no array de origem.

In [40]:
arr_fatia = arr[5:8]
arr_fatia

array([12, 12, 12])

In [41]:
arr_fatia[1] = 1234
arr_fatia

array([  12, 1234,   12])

In [42]:
arr

array([   1,    2,    3,    4,    5,   12, 1234,   12,    9,   10])

In [43]:
arr_fatia[:] = 0
arr

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

**POR QUE ISSO ACONTECE?** Como o NumPy foi projetado para funcionar com matrizes muito grandes, você pode imaginar problemas de desempenho e memória se o NumPy insistir em sempre copiar dados.

In [44]:
arr_copia = arr[:].copy()
arr_copia

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

In [45]:
arr_fatia = arr[5:8]
arr_fatia[:] = -1
arr_fatia

array([-1, -1, -1])

In [46]:
arr_copia

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

In [47]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2d[2]

array([7, 8, 9])

In [49]:
#Podemos acessar um elemento aij da matriz A de duas formas:
print(arr2d[0][2]) # a[i][j]
print(arr2d[0, 2]) #a[i,j]

3
3


In [50]:
arr2d[0, 2] + arr2d[1, 1] 

8

In [51]:
arr2d[:2] # seleciona as duas primeiras linhas de arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [53]:
arr2d[:, 2] # seleciona todas as linhas da terceira coluna

array([3, 6, 9])

In [54]:
print(arr2d[2, :])
print(arr2d[2, :].shape)
arr2d[2, :]

[7 8 9]
(3,)


array([7, 8, 9])

In [55]:
print(arr2d[2:, :])
print(arr2d[2:, :].shape)
arr2d[2:, :]

[[7 8 9]]
(1, 3)


array([[7, 8, 9]])

**Cuidado!*** Os arrays aparentemente são iguais, mas as dimensões deles são diferentes. O primeiro é um vetor coluna e o segundo, um vetor linha. 

### Indexação Booleana

In [56]:
nomes = np.array(['Ana', 'Carol', 'Walter', 'Carol', 'Ana', 'Hugo', 'Hugo'])
print(nomes)

['Ana' 'Carol' 'Walter' 'Carol' 'Ana' 'Hugo' 'Hugo']


In [57]:
nomes == 'Carol'

array([False,  True, False,  True, False, False, False])

In [58]:
dados = np.random.random((7, 4))
dados

array([[0.72487993, 0.65556493, 0.88351164, 0.53046533],
       [0.50120053, 0.28272238, 0.78341881, 0.57474774],
       [0.15098122, 0.6266136 , 0.01992961, 0.46428909],
       [0.90514792, 0.06943299, 0.74144512, 0.36605032],
       [0.99111815, 0.63780908, 0.27285523, 0.4029137 ],
       [0.73761836, 0.6184988 , 0.55440038, 0.20239453],
       [0.35018181, 0.30217218, 0.53862334, 0.06913071]])

A matriz booleana deve ter o mesmo comprimento que o eixo da matriz que está indexando!

In [59]:
#dados[nomes == 'Carol']
dados[nomes == 'Carol',:]

array([[0.50120053, 0.28272238, 0.78341881, 0.57474774],
       [0.90514792, 0.06943299, 0.74144512, 0.36605032]])

In [60]:
dados[nomes == 'Carol',1]

array([0.28272238, 0.06943299])

In [61]:
dados[nomes != 'Carol',:]

array([[0.72487993, 0.65556493, 0.88351164, 0.53046533],
       [0.15098122, 0.6266136 , 0.01992961, 0.46428909],
       [0.99111815, 0.63780908, 0.27285523, 0.4029137 ],
       [0.73761836, 0.6184988 , 0.55440038, 0.20239453],
       [0.35018181, 0.30217218, 0.53862334, 0.06913071]])

In [62]:
dados[~(nomes == 'Carol'),:]

array([[0.72487993, 0.65556493, 0.88351164, 0.53046533],
       [0.15098122, 0.6266136 , 0.01992961, 0.46428909],
       [0.99111815, 0.63780908, 0.27285523, 0.4029137 ],
       [0.73761836, 0.6184988 , 0.55440038, 0.20239453],
       [0.35018181, 0.30217218, 0.53862334, 0.06913071]])

In [63]:
dados[(nomes == 'Carol') | (nomes == 'Walter'),:] # & (and),  | (or)

array([[0.50120053, 0.28272238, 0.78341881, 0.57474774],
       [0.15098122, 0.6266136 , 0.01992961, 0.46428909],
       [0.90514792, 0.06943299, 0.74144512, 0.36605032]])

In [64]:
dados[dados<0.5]

array([0.28272238, 0.15098122, 0.01992961, 0.46428909, 0.06943299,
       0.36605032, 0.27285523, 0.4029137 , 0.20239453, 0.35018181,
       0.30217218, 0.06913071])

In [65]:
dados[dados<0.5].shape

(12,)

In [66]:
dados[dados[:,1]<0.5]

array([[0.50120053, 0.28272238, 0.78341881, 0.57474774],
       [0.90514792, 0.06943299, 0.74144512, 0.36605032],
       [0.35018181, 0.30217218, 0.53862334, 0.06913071]])

In [67]:
dados[dados[:,1]<0.5].shape

(3, 4)

In [68]:
arr = np.array([1, 2, 3, np.nan, np.nan, 4])
arr

array([ 1.,  2.,  3., nan, nan,  4.])

In [69]:
np.isnan(arr)

array([False, False, False,  True,  True, False])

In [70]:
arr[~np.isnan(arr)]

array([1., 2., 3., 4.])

### Removendo Duplicatas

In [71]:
nomes

array(['Ana', 'Carol', 'Walter', 'Carol', 'Ana', 'Hugo', 'Hugo'],
      dtype='<U6')

In [72]:
np.unique(nomes) # é o mesmo que fazer sorted(set(names))

array(['Ana', 'Carol', 'Hugo', 'Walter'], dtype='<U6')

In [73]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

### Estatísticas

<img src="../Figuras/eixos.jpg" alt="drawing" width="500"/>

In [74]:
arr = np.random.randint(1, 11, (2,3))
arr

array([[7, 4, 6],
       [4, 2, 5]])

In [75]:
print(arr.mean())
print(arr.mean(axis=0)) # eixo 0: média das linhas de cada coluna
print(arr.mean(axis=1)) # eixo 1: média das colunas de cada linha

4.666666666666667
[5.5 3.  5.5]
[5.66666667 3.66666667]


In [76]:
print(arr.sum())
print(arr.sum(axis=0)) # eixo 0: soma das linhas de cada coluna
print(arr.sum(axis=1)) # eixo 1: soma das colunas de cada linha

28
[11  6 11]
[17 11]


In [77]:
print(arr.cumsum())
print()
print(arr.cumsum(axis=0)) # eixo 0: soma acumulada das linhas de cada coluna
print()
print(arr.cumsum(axis=1)) # eixo 1: soma acumulada das colunas de cada linha

[ 7 11 17 21 23 28]

[[ 7  4  6]
 [11  6 11]]

[[ 7 11 17]
 [ 4  6 11]]


### Ordenamento

In [78]:
arr = np.random.randint(1, 11, (4,5))
print(arr)
print()
arr.sort(0) # ordenamento dos elementos das linhas de cada coluna
print(arr)
print()
arr.sort(1) # ordenamento dos elementos das colunas de cada linha
print(arr)

[[ 3  2  5  3  8]
 [ 2  3  1  7  7]
 [ 5  4  6  1  3]
 [10  3  8  7  6]]

[[ 2  2  1  1  3]
 [ 3  3  5  3  6]
 [ 5  3  6  7  7]
 [10  4  8  7  8]]

[[ 1  1  2  2  3]
 [ 3  3  3  5  6]
 [ 3  5  6  7  7]
 [ 4  7  8  8 10]]


### Concatenação

In [79]:
c = np.array([1,2,3])
l = np.array([[1],[2],[3]])
m = np.array([[1, 2, 3], [4, 5, 6]])

In [80]:
np.concatenate((c.reshape(len(c),1), np.ones(len(c)).reshape(len(c),1)),axis=1)

array([[1., 1.],
       [2., 1.],
       [3., 1.]])

In [81]:
np.concatenate((l.reshape(len(l),1), np.ones(len(l)).reshape(len(l),1)),axis=1)

array([[1., 1.],
       [2., 1.],
       [3., 1.]])

In [82]:
np.concatenate((m, np.ones(len(m)).reshape(len(m),1)),axis=1)

array([[1., 2., 3., 1.],
       [4., 5., 6., 1.]])

In [83]:
len(m) == m.shape[0]

True

In [84]:
np.concatenate((m, np.ones(m.shape[1]).reshape(1,m.shape[1])),axis=0)

array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 1., 1.]])

### Álgebra Linear

In [85]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [86]:
y = np.array([[6, 23], [-1, 7], [8, 9]])
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [87]:
# x.dot(y) ou np.dot(x,y): calcula a multiplicação entre as matrizes x e y
x.dot(y)  

array([[ 28.,  64.],
       [ 67., 181.]])

In [88]:
z = x.dot(y)

In [89]:
# z.T: calcula a matriz transposta de z
print(z.transpose())
z.T

[[ 28.  67.]
 [ 64. 181.]]


array([[ 28.,  67.],
       [ 64., 181.]])

In [90]:
z.T.T 

array([[ 28.,  64.],
       [ 67., 181.]])

In [91]:
np.array([1,2,3]).T.shape == np.array([1,2,3]).shape

True

In [92]:
np.array([1,2,3]).reshape(3,1)

array([[1],
       [2],
       [3]])

In [93]:
from numpy.linalg import inv, det, qr, eig, solve, lstsq

In [94]:
# det: calcula o determinante da matriz
print((z[0,0]*z[1,1])-(z[0,1]*z[1,0]))
print(det(z))

780.0
779.9999999999994


In [95]:
# inv(z): calcula a inversa de uma matriz quadrada
inv(z)

array([[ 0.23205128, -0.08205128],
       [-0.08589744,  0.03589744]])

In [96]:
I = z.dot(inv(z))
I

array([[ 1.00000000e+00, -4.44089210e-16],
       [ 2.63677968e-16,  1.00000000e+00]])

In [97]:
# np.diag(I)
print(I.diagonal(0)) # diagonal principal
print(I.diagonal(1))
print(I.diagonal(-1))
print(np.fliplr(I).diagonal(0)) # uma forma de calcular a diagonal secundária

[1. 1.]
[-4.4408921e-16]
[2.63677968e-16]
[-4.44089210e-16  2.63677968e-16]


`np.flplr()`: gira as entradas em cada linha na direção esquerda / direita. As colunas são preservadas, mas aparecem em uma ordem diferente da anterior.

In [98]:
I.trace() # calcula o traço da matriz (soma dos elementos da diagonal principal)
#np.trace(I)

2.000000000000001

**Decmposição QR**: trasnforma $A$ em um produto $A = QR$ de uma matriz ortogonal $Q$ e uma matriz triangular superior $R$.

In [99]:
q, r = qr(z)
print(q)
print()
print(r)

[[-0.385593   -0.92266897]
 [-0.92266897  0.385593  ]]

[[ -72.61542536 -191.68103652]
 [   0.           10.7415194 ]]


**Autovetores** e **Autovalores** de uma matriz quadrada.  

In [100]:
w,v = eig(z)
print(w) # autovalores
print() 
print(v) # autovetores

[  3.80119167 205.19880833]

[[-0.93537044 -0.33969866]
 [ 0.35366953 -0.94053433]]


Resolver o sistema de equações lineares:
$$3\cdot x_0 + x_1 = 9 \\  x_0 + 2\cdot x_1 = 8 $$

In [101]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = solve(a, b)
x

array([2., 3.])

In [102]:
# Testa a solução
np.allclose(np.dot(a, x), b) # dois arrays são iguais com uma certa tolerância

True

## Tipo Matriz

In [103]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,9],[7,5]])

In [104]:
a

array([[1, 2],
       [3, 4]])

In [105]:
b

array([[1, 9],
       [7, 5]])

In [106]:
a*b

array([[ 1, 18],
       [21, 20]])

In [107]:
A = np.matrix(a)
B = np.matrix(b)

In [108]:
A

matrix([[1, 2],
        [3, 4]])

In [109]:
B

matrix([[1, 9],
        [7, 5]])

In [110]:
A*B

matrix([[15, 19],
        [31, 47]])

In [111]:
print(type(a))
print(type(A))
print(type(a*b))
print(type(A*B))
print(type(a*B))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.matrix'>
<class 'numpy.matrix'>


In [112]:
np.matrix([1,2,3]).T

matrix([[1],
        [2],
        [3]])

In [113]:
np.array([1,2,3]).T

array([1, 2, 3])