# Lista de Exercícios: Vetores e Matrizes

In [1]:
import numpy as np
import math as mt
import pandas as pd

## Exercício 1

Implementar a ordenação de arrays pelo método do [Bubble Sort](https://pt.wikipedia.org/wiki/Bubble_sort).

In [2]:
def bubble_Julia(lista):
    for i in range (0,len(lista)-1):
        x=lista[i]
        y=lista[i+1]
        if x>y:
            lista[i+1]=x
            lista[i]=y
    for i in range (0,len(lista)-1):
        x=lista[i]
        y=lista[i+1]
        if x>y:
            bubble_Julia(lista)
    return lista

In [3]:
def meu_bobo_sort(lista):
    houvetroca=1
    passadas=0 #serve para controlar o loop e evitar que vá até o final da lista desnecessariamente
    while houvetroca==1:
        houvetroca=0
        for i in range(len(lista)-1-passadas):
            if lista[i]>lista[i+1]:
                aux=lista[i+1]
                lista[i+1]=lista[i]
                lista[i]=aux
                houvetroca=1
        passadas=passadas+1
    return lista
                

In [4]:
meu_bobo_sort([1,5,10,2,8,4,3,20])

[1, 2, 3, 4, 5, 8, 10, 20]

## Exercício 2

Somar duas matrizes, por meio de uma soma dos elementos correspondentes (soma elemento a elemento). Ou seja, sejam $A$ e $B$ as matrizes que serão somadas, cada elemento da matriz resultante $C$ será dado por:

$$c_{ij}= a_{ij} + b_{ij}$$

In [5]:
def somamat(a,b):
    #soma os elementos correspondentes de duas matrizes
    if a.shape!=b.shape:
        print ("Erro: Matrizes de dimensões diferentes")
        return nan
    c=np.matrix(np.zeros(a.shape))
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            c[i,j]=a[i,j]+b[i,j]
    return c

In [6]:
z=np.matrix([[1,2,3],[5,6,7]])
y=np.matrix([[10,20,30],[50,60,70]])

In [7]:
somamat(z,y)

matrix([[11., 22., 33.],
        [55., 66., 77.]])

## Exercício 3

Criar uma função que recebe uma matriz como parâmetro de entrada e troca 2 linhas escolhidas (parâmetros de entrada) de posição. 

In [8]:
def trocalinhas(mat,l1,l2):
    #troca as linhas l1 e l2 da matriz mat de posição
    for i in range (mat.shape[1]):
        aux=mat[l1,i]
        mat[l1,i]=mat[l2,i]
        mat[l2,i]=aux
    return mat

In [9]:
tr=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
tr

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [10]:
trocalinhas(tr,2,0)

matrix([[ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

## Exercício 4

Criar uma função que recebe uma matriz como parâmetro de entrada e inverte a ordem das linhas dessa matriz. 

In [11]:
def trocatudo(mat):
    nlin=mat.shape[0]
    ncol=mat.shape[1]
    for i in range(nlin//2):
        for j in range (ncol):
            aux=mat[i,j]
            mat[i,j]=mat[(nlin-i-1),j]
            mat[(nlin-i-1),j]=aux
    return mat

In [12]:
tr=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
tr

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [13]:
trocatudo(tr)

matrix([[17, 18, 19, 20],
        [13, 14, 15, 16],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4]])

## Exercício 5

Criar uma função para multiplicar duas matrizes, pela implementação do método de multiplicação matricial (não usar a função de multiplicação de matrizes do Python)

In [14]:
def matmult(a,b):
    #multiplica as matrizes a e b "na marra", sem usar a função de multiplicação de matrizes do NumPy
    nlina=a.shape[0]
    ncola=a.shape[1]
    nlinb=b.shape[0]
    ncolb=b.shape[1]
    if ncola!=nlinb:
        print("Dimensões incompatíveis")
        return nan
    nlinc=nlina
    ncolc=ncolb
    c=np.zeros((nlinc,ncolc))
    for i in range (nlinc):
        for j in range (ncolc):
            c[i,j]=0
            for k in range (ncola):
                c[i,j]=c[i,j]+a[i,k]*b[k,j]
    return c
                

In [15]:
tr1=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
tr2=np.matrix([[1,2],[5,6],[9,10],[13,14]])

In [16]:
matmult(tr1,tr2)

array([[ 90., 100.],
       [202., 228.],
       [314., 356.],
       [426., 484.],
       [538., 612.]])

In [17]:
x=tr1*tr2
x

matrix([[ 90, 100],
        [202, 228],
        [314, 356],
        [426, 484],
        [538, 612]])

## Exercício 6

Contar os pontos do boliche. Use os dados da planilha disponível na pasta da disciplina na rede.

## Exercício 7

Campo minado: Defina o tamanho do quadro do jogo e a quantidade de bombas no quadro. Crie uma função que recebe a lista com a posicões das bombas e retorne uma matriz, com o tamanho do quadro, em que cada célula contém a quantidade de bombas presentes nas células vizinhas.

In [54]:
bombas=np.asmatrix([[0,2],[0,3],[1,6],[2,2],[2,7],[3,0],[3,4],[4,6],[5,2],[6,5]])
bombas

matrix([[0, 2],
        [0, 3],
        [1, 6],
        [2, 2],
        [2, 7],
        [3, 0],
        [3, 4],
        [4, 6],
        [5, 2],
        [6, 5]])

In [81]:
def campominado(bombas,tamanho):
    campo=np.zeros([tamanho,tamanho])
    for b in range (bombas.shape[0]):
        #marca a célula da bomba com "nan"
        campo[bombas[b,0],bombas[b,1]]=np.nan
        #aumenta a quantidade de bombas nas células vizinhas
        #esquerda
        if bombas[b,1]>0:
            campo[bombas[b,0],bombas[b,1]-1]=campo[bombas[b,0],bombas[b,1]-1]+1
        #direita
        if bombas[b,1]<tamanho-2:
            campo[bombas[b,0],bombas[b,1]+1]=campo[bombas[b,0],bombas[b,1]+1]+1
        #em cima
        if bombas[b,0]>0:
            campo[bombas[b,0]-1,bombas[b,1]]=campo[bombas[b,0]-1,bombas[b,1]]+1
        #em baixo
        if bombas[b,0]<tamanho-2:
            campo[bombas[b,0]+1,bombas[b,1]]=campo[bombas[b,0]+1,bombas[b,1]]+1
        #FALTA ACERTAR AS CÉLULAS NA DIAGONAL
    return campo

In [80]:
campominado(bombas,8)

array([[ 0.,  1., nan, nan,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  2.,  1.,  0.,  1., nan,  1.],
       [ 1.,  1., nan,  1.,  1.,  0.,  2., nan],
       [nan,  1.,  1.,  1., nan,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  1., nan,  0.],
       [ 0.,  1., nan,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  1., nan,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## Exercício 8

Calcular o [determinante](https://pt.wikipedia.org/wiki/Determinante) de uma matriz usando o **método de escalonamento**. 

In [2]:
def det(a):
    #calcula o determinante da matriz pelo método do escalonamento
    nlins=a.shape[0]
    ncols=a.shape[1]
    mult=1
    for linbase in range(nlins):
        #pega o elemento da diagonal como fator da linha base
        fator=a[linbase,linbase]
        mult=mult*fator
        #divide os elementos da linha base pelo fator, pra ficar com 1 na diagonal
        for col in range(ncols):
            a[linbase,col]=a[linbase,col]/fator
        #substitui os elementos das linhas abaixo de forma a fazer os elementos abaixo do fator ficarem com zero
        for lin in range (linbase+1,nlins):
            #pega como "pivô" o elemento da linha que está na coluna do fator da linha base 
            pivo=a[lin,linbase]
            for col in range(ncols):
                a[lin,col]=a[lin,col]-pivo*a[linbase,col]
        #print (mat)
    return mult


In [3]:
mat=np.matrix([[4.,1.,2.],[3.,2.,0.],[2.,-1.,1.]])
mat

matrix([[ 4.,  1.,  2.],
        [ 3.,  2.,  0.],
        [ 2., -1.,  1.]])

In [4]:
det(mat)

-9.0

## Exercício 9

Calcular o [determinante](https://pt.wikipedia.org/wiki/Teorema_de_Laplace) de uma matriz usando o **método dos cofatores** (recursivo).

In [7]:
def detcof(a):
    #calcula o determinante da matriz pelo método dos cofatores (recursivo)
    nlins=a.shape[0]
    ncols=a.shape[1]
    #cofs=np.zeros((1,ncols))
    if nlins==1 and ncols==1:
        return a[0,0]
    #calcula o determinante com base nos cofatores dos elementos da primeira linha
    det=0
    for elemento in range(ncols): #pega todos os elementos da primeira linha da matriz, calcula o cofator e o menor
        menor=np.zeros((nlins-1,ncols-1))
        cof=((-1)**elemento)*a[0,elemento]
        for lin in range(1,nlins): #pega as linhas abaixo da primeira
            colmenor=0
            for col in range(ncols):
                if col!=elemento:
                    menor[lin-1,colmenor]=a[lin,col]
                    colmenor=colmenor+1
            det=det+cof*detcof(menor)
    return det


In [8]:
mat=np.matrix([[4.,1.,2.],[3.,2.,0.],[2.,-1.,1.]])
mat

matrix([[ 4.,  1.,  2.],
        [ 3.,  2.,  0.],
        [ 2., -1.,  1.]])

In [9]:
detcof(mat)

-9.0

## Exercício 10

a) Criar uma função que recebe como parâmetros de entrada (i) uma matriz de dados; e (ii) um valor a ser procurado, e retorna como parâmetros de saída (i) a quantidade de vezes que este valor aparece na matriz, e (ii) uma lista com as posições (linha coluna) onde esses valores são encontrados

b) Criar uma função que recebe como parâmetros de entrada uma matriz de dados e uma sequência de valores (array ou lista), e localiza a sequência na matriz, retornando a lista com as posições $(i,j)$ onde a sequência foi encontrada.

In [27]:
def contaocorr(matriz,valor):
    #conta quantas vezes o "valor" aparece na "matriz"
    cont=0
    lista=[]
    for i in range(matriz.shape[0]):
        for j in range (matriz.shape[1]):
            if matriz[i,j]==valor:
                cont=cont+1
                lista.append([i,j])
    return cont,lista

In [50]:
dados=np.matrix(pd.read_excel("Documents\ocorrencias.xlsx",header=None))
seq1=np.matrix(pd.read_excel("Documents\ocorrencias.xlsx",header=None,sheet_name="seq1"))
seq2=np.matrix(pd.read_excel("Documents\ocorrencias.xlsx",header=None,sheet_name="seq2"))
seq3=np.matrix(pd.read_excel("Documents\ocorrencias.xlsx",header=None,sheet_name="seq3"))

In [28]:
contaocorr(dados,20)

(119,
 [[4, 14],
  [9, 29],
  [12, 29],
  [20, 23],
  [28, 30],
  [30, 5],
  [37, 2],
  [39, 12],
  [51, 3],
  [52, 1],
  [52, 40],
  [59, 15],
  [60, 20],
  [63, 25],
  [66, 21],
  [71, 9],
  [73, 37],
  [77, 45],
  [81, 6],
  [81, 46],
  [83, 26],
  [84, 25],
  [84, 40],
  [91, 10],
  [91, 11],
  [93, 44],
  [95, 18],
  [97, 43],
  [99, 8],
  [104, 38],
  [109, 6],
  [113, 29],
  [115, 45],
  [117, 21],
  [118, 49],
  [120, 33],
  [124, 15],
  [130, 2],
  [135, 5],
  [137, 43],
  [137, 47],
  [139, 31],
  [147, 7],
  [156, 47],
  [163, 38],
  [165, 12],
  [165, 14],
  [171, 17],
  [175, 43],
  [181, 37],
  [190, 18],
  [190, 34],
  [194, 9],
  [195, 23],
  [197, 13],
  [197, 32],
  [199, 37],
  [206, 8],
  [215, 24],
  [224, 28],
  [224, 43],
  [229, 22],
  [233, 8],
  [235, 20],
  [236, 33],
  [259, 26],
  [274, 14],
  [284, 30],
  [285, 1],
  [287, 49],
  [293, 13],
  [300, 12],
  [308, 34],
  [318, 13],
  [323, 24],
  [324, 45],
  [329, 26],
  [330, 23],
  [344, 13],
  [345, 49],


In [51]:
def contaocorr2(matriz,seq):
    #conta quantas vezes a sequência "seq" aparece na "matriz", e identifica as posições das ocorrências
    cont=0
    lista=[]
    nlin=matriz.shape[0]
    ncol=matriz.shape[1]
    tamanho=seq.shape[1]
    primeiro=seq[0,0]
    for i in range(matriz.shape[0]): #todas as linhas da matriz
        for j in range (ncol-tamanho+1): #todas as colunas, até a última possível
            if matriz[i,j]==primeiro:  #se encontrou o primeiro elemento da sequência, vai tentar achar os demais
                achou=1
                ind=1
                while achou==1 and ind <tamanho:
                    if matriz[i,j+ind]!=seq[0,ind]:
                        achou=0
                    ind=ind+1
                if achou==1:
                    cont=cont+1
                    lista.append([i,j])
    return cont,lista

In [53]:
contaocorr2(dados,seq1),contaocorr2(dados,seq2),contaocorr2(dados,seq3)

((3, [[14, 3], [66, 25], [115, 45]]),
 (5, [[4, 19], [19, 2], [20, 37], [281, 34], [439, 16]]),
 (2, [[10, 40], [36, 4]]))

## Exercício 11

Troca-troca de figurinhas: Criar uma função que recebe dois pares de listas, representando as figurinhas de dois jogadores: para cada jogador, passe a lista de figurinhas que ele precisa e a lista de figurinhas que ele tem duplicatas. Retorne com a lista de trocas que esses dois jogadores podem fazer entre si.