# Lista de Exercícios: Vetores e Matrizes

In [2]:
import numpy as np
import math as mt

## Exercício 1

Implementar a ordenação de arrays pelo método do [Bubble Sort](https://pt.wikipedia.org/wiki/Bubble_sort).

In [3]:
def bubble_Julia(lista):
    for i in range (0,len(lista)-1):
        x=lista[i]
        y=lista[i+1]
        if x>y:
            lista[i+1]=x
            lista[i]=y
    for i in range (0,len(lista)-1):
        x=lista[i]
        y=lista[i+1]
        if x>y:
            bubble_Julia(lista)
    return lista

In [7]:
def meu_bobo_sort(lista):
    houvetroca=1
    passadas=0 #serve para controlar o loop e evitar que vá até o final da lista desnecessariamente
    while houvetroca==1:
        houvetroca=0
        for i in range(len(lista)-1-passadas):
            if lista[i]>lista[i+1]:
                aux=lista[i+1]
                lista[i+1]=lista[i]
                lista[i]=aux
                houvetroca=1
        passadas=passadas+1
    return lista
                

In [9]:
meu_bobo_sort([1,5,10,2,8,4,3,20])

[1, 2, 3, 4, 5, 8, 10, 20]

## Exercício 2

Somar duas matrizes, por meio de uma soma dos elementos correspondentes (soma elemento a elemento). Ou seja, sejam $A$ e $B$ as matrizes que serão somadas, cada elemento da matriz resultante $C$ será dado por:

$$c_{ij}= a_{ij} + b_{ij}$$

In [21]:
def somamat(a,b):
    #soma os elementos correspondentes de duas matrizes
    if a.shape!=b.shape:
        print ("Erro: Matrizes de dimensões diferentes")
        return nan
    c=np.matrix(np.zeros(a.shape))
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            c[i,j]=a[i,j]+b[i,j]
    return c

In [19]:
z=np.matrix([[1,2,3],[5,6,7]])
y=np.matrix([[10,20,30],[50,60,70]])

In [22]:
somamat(z,y)

matrix([[11., 22., 33.],
        [55., 66., 77.]])

## Exercício 3

Criar uma função que recebe uma matriz como parâmetro de entrada e troca 2 linhas escolhidas (parâmetros de entrada) de posição. 

In [23]:
def trocalinhas(mat,l1,l2):
    #troca as linhas l1 e l2 da matriz mat de posição
    for i in range (mat.shape[1]):
        aux=mat[l1,i]
        mat[l1,i]=mat[l2,i]
        mat[l2,i]=aux
    return mat

In [24]:
tr=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
tr

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [27]:
trocalinhas(tr,2,0)

matrix([[17, 18, 19, 20],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [ 9, 10, 11, 12]])

## Exercício 4

Criar uma função que recebe uma matriz como parâmetro de entrada e inverte a ordem das linhas dessa matriz. 

## Exercício 5

Criar uma função para multiplicar duas matrizes, pela implementação do método de multiplicação matricial (não usar a função de multiplicação de matrizes do Python)

## Exercício 6

Contar os pontos do boliche. Use os dados da planilha disponível na pasta da disciplina na rede.

## Exercício 7

Campo minado: Defina o tamanho do quadro do jogo e a quantidade de bombas no quadro. Crie uma função que recebe a lista com a posicões das bombas e retorne uma matriz, com o tamanho do quadro, em que cada célula contém a quantidade de bombas presentes nas células vizinhas.

## Exercício 8

Calcular o [determinante](https://pt.wikipedia.org/wiki/Determinante) de uma matriz usando o **método de escalonamento**. 

## Exercício 9

Calcular o [determinante](https://pt.wikipedia.org/wiki/Teorema_de_Laplace) de uma matriz usando o **método dos cofatores** (recursivo).

## Exercício 10

Criar uma função que recebe como parâmetros de entrada uma matriz de dados e uma sequência de valores (array ou lista), e localiza a sequência na matriz, retornando a lista com as posições $(i,j)$ onde a sequência foi encontrada.

## Exercício 11

Troca-troca de figurinhas: Criar uma função que recebe dois pares de listas, representando as figurinhas de dois jogadores: para cada jogador, passe a lista de figurinhas que ele precisa e a lista de figurinhas que ele tem duplicatas. Retorne com a lista de trocas que esses dois jogadores podem fazer entre si.